### ISSUE TITLE
Installation of Petrinet & pm4py

### ISSUE THREAD

**Issue by dupadhyaya** [bupaverse/petrinetR#6] opened 2020-06-14 17:19 UTC
I have problems in install and using this library. Cannot understand what could be the issue.
The problems is more related to pm4py. I have both miniconda and anaconda installed. Can you explain the steps for a person who is first time installing with any version of Python in their system.
Because of this unable to perform an important part of PM. Some video tutorial will also help. 
Thanks.  Dhiraj

**Comment by gertjanssenswillen** [comment] 2020-06-14 17:21
Sorry, but we can't really help if we don't know what the problem is. Please check information here: https://bupaverse.github.io/pm4py/

**Comment by gertjanssenswillen** [comment] 2020-06-14 18:21
I close this issue, as there is already this: https://github.com/bupaverse/pm4py/issues/8

**Closed as completed by gertjanssenswillen** 2020-06-14 18:21 UTC
